TEAM_NAME_MAPPING = {
    "1.FC Heidenheim 1846": "FC Heidenheim",
    "1.FC Kaiserslautern": "Kaiserslautern",
    "1.FC Köln": "FC Köln",
    "1.FC Magdeburg": "Magdeburg",
    "1.FC Nuremberg": "Nurnberg",
    "1.FC Union Berlin": "Union Berlin",
    "1.FSV Mainz 05": "FSV Mainz 05",
    "AC Ajaccio": "AC Ajaccio",
    "AC Arles-Avignon": "Arles",
    "AC Cesena": "Cesena",
    "AC Milan": "AC Milan",
    "AC Monza": "Monza",
    "AC Perugia Calcio": "Perugia",
    "AC Pisa 1909": "Pisa",
    "AC Reggiana 1919": "Reggiana",
    "ACF Fiorentina": "Fiorentina",
    "AD Alcorcón": "AD Alcorcón",
    "AD Ceuta FC": "Ceuta",
    "ADO Den Haag": "Den Haag",
    "AE Kifisia": "Kifisia",
    "AE Larisa": "Larisa",
    "AEK Athens": "AEK Athens",
    "AEL Kalloni": "AEL Kalloni",
    "AFC Bournemouth": "AFC Bournemouth",
    "AJ Auxerre": "Auxerre",
    "AOK Kerkyra": "Kerkyra",
    "AS Avellino 1912": "Avellino",
    "AS Béziers": "Beziers",
    "AS Cittadella": "Cittadella",
    "AS Livorno": "Livorno",
    "AS Monaco": "AS Monaco",
    "AS Nancy-Lorraine": "Nancy",
    "AS Roma": "AS Roma",
    "AS Saint-Étienne": "Saint-Étienne",
    "AZ Alkmaar": "AZ Alkmaar",
    "Académica Coimbra": "Académica Coimbra",
    "Adana Demirspor": "Ad. Demirspor",
    "Adanaspor": "Adanaspor",
    "Ajax Amsterdam": "Ajax Amsterdam",
    "Akhisar Belediyespor": "Akhisar Belediyespor",
    "Akhisarspor": "Akhisarspor",
    "Alanyaspor": "Alanyaspor",
    "Albacete Balompié": "Albacete",
    "Almere City FC": "Almere City",
    "Altay SK": "Altay",
    "Amiens SC": "Amiens",
    "Angers SCO": "Angers",
    "Antalyaspor": "Antalyaspor",
    "Apollon Smyrni": "Apollon",
    "Aris Thessaloniki": "Aris Thessaloniki",
    "Arminia Bielefeld": "Bielefeld",
    "Arsenal FC": "Arsenal",
    "Ascoli Calcio": "Ascoli",
    "Ascoli Picchio": "Ascoli",
    "Asteras Aktor": "Asteras Aktor",
    "Asteras Tripolis": "Asteras Tripolis",
    "Aston Villa": "Aston Villa",
    "Atalanta BC": "Atalanta",
    "Athens Kallithea": "Athens Kallithea",
    "Athletic Bilbao": "Athletic Bilbao",
    "Atlético de Madrid": "Atletico Madrid",
    "Atromitos Athens": "Atromitos",
    "Avs Futebol": "Avs Futebol",
    "B SAD (2018-2024)": "B SAD (2018-2024)",
    "Balikesirspor": "Balikesirspor",
    "Barnsley FC": "Barnsley",
    "Basaksehir FK": "Basaksehir FK",
    "Bayer 04 Leverkusen": "Bayer Leverkusen",
    "Bayern Munich": "Bayern Munich",
    "Beerschot VA": "Beerschot VA",
    "Benevento Calcio": "Benevento",
    "Besiktas JK": "Besiktas",
    "Bilbao Athletic": "Bilbao Athletic",
    "Birmingham City": "Birmingham City",
    "Blackburn Rovers": "Blackburn Rovers",
    "Blackpool FC": "Blackpool",
    "Boavista FC": "Boavista",
    "Bodrum FK": "Bodrum FK",
    "Bologna FC 1909": "Bologna",
    "Bolton Wanderers": "Bolton Wanderers",
    "Borussia Dortmund": "Borussia Dortmund",
    "Borussia Mönchengladbach": "Borussia Mönchengladbach",
    "Brentford FC": "Brentford",
    "Brescia Calcio": "Brescia",
    "Brescia Calcio (- 2025)": "Brescia",
    "Brighton & Hove Albion": "Brighton & Hove Albion",
    "Bristol City": "Bristol City",
    "Burgos CF": "Burgos",
    "Burnley FC": "Burnley",
    "Bursaspor": "Bursaspor",
    "Burton Albion": "Burton",
    "Büyüksehir Belediye Erzurumspor": "Büyüksehir Belediye Erzurumspor",
    "CA Osasuna": "CA Osasuna",
    "CD Castellón": "Castellon",
    "CD Eldense": "Eldense",
    "CD Feirense": "Feirense",
    "CD Leganés": "Leganés",
    "CD Lugo": "Lugo",
    "CD Mirandés": "Mirandes",
    "CD Nacional": "Nacional",
    "CD Numancia": "CD Numancia de Soria",
    "CD Santa Clara": "Santa Clara",
    "CD Tenerife": "Tenerife",
    "CD Tondela": "Tondela",
    "CE Sabadell FC": "Sabadell",
    "CF Estrela Amadora": "Estrela",
    "CF Fuenlabrada": "Fuenlabrada",
    "CF Os Belenenses": "Belenenses",
    "CF Rayo Majadahonda": "Rayo Majadahonda",
    "CF Reus Deportiu": "Reus Deportiu",
    "CF União Madeira (-2021)": "CF União Madeira (-2021)",
    "CS Marítimo": "CS Marítimo",
    "Cagliari Calcio": "Cagliari",
    "Calcio Catania": "Catania",
    "Calcio Como": "Calcio Como",
    "Calcio Lecco 1912": "Lecco",
    "Calcio Padova": "Padova",
    "Cardiff City": "Cardiff",
    "Carpi FC 1909": "Carpi",
    "Carrarese Calcio 1908": "Carrarese",
    "Casa Pia AC": "Casa Pia",
    "Caykur Rizespor": "Rizespor",
    "Celta de Vigo": "Celta Vigo",
    "Cercle Brugge": "Cercle Brugge",
    "Cesena FC": "Cesena",
    "Chamois Niortais FC": "Niort",
    "Charlton Athletic": "Charlton Athletic",
    "Chelsea FC": "Chelsea",
    "Chievo Verona": "Chievo",
    "Clermont Foot 63": "Clermont Foot",
    "Club Brugge KV": "Club Brugge",
    "Como 1907": "Como",
    "Cosenza Calcio": "Cosenza",
    "Coventry City": "Coventry",
    "Crystal Palace": "Crystal Palace",
    "Cultural Leonesa": "Cultural Leonesa",
    "Cádiz CF": "Cádiz",
    "Córdoba CF": "Córdoba CF",
    "De Graafschap Doetinchem": "Graafschap",
    "Delfino Pescara 1936": "Pescara",
    "Denizlispor": "Denizlispor",
    "Deportivo Alavés": "Deportivo Alavés",
    "Deportivo de La Coruña": "RC Deportivo La Coruña",
    "Derby County": "Derby",
    "Desportivo Aves (- 2020)": "Desportivo Aves (- 2020)",
    "Dijon FCO": "Dijon",
    "EA Guingamp": "Guingamp",
    "ESTAC Troyes": "Troyes",
    "Eintracht Braunschweig": "Braunschweig",
    "Eintracht Frankfurt": "Eintracht Frankfurt",
    "Elche CF": "Elche",
    "Empoli FC": "Empoli",
    "Ergotelis FC": "Ergotelis",
    "Eskisehirspor": "Eskisehirspor",
    "Everton FC": "Everton",
    "Excelsior Rotterdam": "Excelsior",
    "Extremadura UD": "Extremadura UD",
    "Eyüpspor": "Eyupspor",
    "FC Alverca": "Alverca",
    "FC Andorra": "Andorra",
    "FC Annecy": "Annecy",
    "FC Arouca": "Arouca",
    "FC Augsburg": "FC Augsburg",
    "FC Barcelona": "Barcelona",
    "FC Barcelona B": "Barcelona",
    "FC Bari 1908": "Bari",
    "FC Cartagena": "Cartagena",
    "FC Chambly Oise": "Chambly",
    "FC Crotone": "Crotone",
    "FC Dordrecht": "Dordrecht",
    "FC Emmen": "FC Emmen",
    "FC Empoli": "Empoli",
    "FC Erzgebirge Aue": "Erzgebirge Aue",
    "FC Famalicão": "Famalicao",
    "FC Girondins Bordeaux": "Bordeaux",
    "FC Groningen": "Groningen",
    "FC Hansa Rostock": "Hansa Rostock",
    "FC Ingolstadt 04": "Ingolstadt",
    "FC Lorient": "Lorient",
    "FC Martigues": "Martigues",
    "FC Metz": "Metz",
    "FC Nantes": "Nantes",
    "FC Paços de Ferreira": "Pacos Ferreira",
    "FC Penafiel": "Penafiel",
    "FC Porto": "FC Porto",
    "FC Pro Vercelli 1892": "Pro Vercelli",
    "FC Schalke 04": "Schalke 04",
    "FC Sochaux-Montbéliard": "Sochaux",
    "FC St. Pauli": "St Pauli",
    "FC Südtirol": "Sudtirol",
    "FC Toulouse": "Toulouse",
    "FC Twente Enschede": "Twente",
    "FC Utrecht": "Utrecht",
    "FC Vizela": "Vizela",
    "FC Volendam": "Volendam",
    "FC Évian Thonon Gaillard": "Evian Thonon Gaillard",
    "FCV Dender EH": "Dender",
    "FSV Frankfurt": "Frankfurt FSV",
    "Fatih Karagümrük": "Fatih Karagümrük",
    "Fenerbahce": "Fenerbahce",
    "Feralpisalò": "FeralpiSalo",
    "Feyenoord Rotterdam": "Feyenoord",
    "Foggia Calcio": "Foggia",
    "Football Bourg-en-Bresse Péronnas 01": "Football Bourg-en-Bresse Péronnas 01",
    "Fortuna Düsseldorf": "Fortuna Dusseldorf",
    "Fortuna Sittard": "For Sittard",
    "Frosinone Calcio": "Frosinone",
    "Fulham FC": "Fulham",
    "GD Chaves": "Chaves",
    "GD Estoril Praia": "Estoril",
    "GFC Ajaccio": "Ajaccio",
    "Galatasaray": "Galatasaray",
    "Gaziantep FK": "Gaziantep",
    "Gaziantepspor": "Gaziantepspor",
    "Genclerbirligi Ankara": "Genclerbirligi",
    "Genoa CFC": "Genoa",
    "Getafe CF": "Getafe",
    "Gil Vicente FC": "Gil Vicente",
    "Gimnàstic de Tarragona": "Gimnàstic Tarragona",
    "Giresunspor": "Giresunspor",
    "Girona FC": "Girona",
    "Go Ahead Eagles": "Go Ahead Eagles",
    "Granada CF": "Granada",
    "Grenoble Foot 38": "Grenoble",
    "Göztepe": "Goztep",
    "Hamburger SV": "Hamburger SV",
    "Hannover 96": "Hannover 96",
    "Hatayspor": "Hatayspor",
    "Hellas Verona": "Hellas Verona",
    "Heracles Almelo": "Heracles",
    "Hertha BSC": "Hertha",
    "Holstein Kiel": "Holstein Kiel",
    "Huddersfield Town": "Huddersfield",
    "Hull City": "Hull City",
    "Inter Milan": "Inter Milan",
    "Ionikos Nikea": "Ionikos",
    "Ipswich Town": "Ipswich",
    "Iraklis Thessaloniki": "Iraklis",
    "Istanbulspor": "Istanbulspor",
    "Juventus FC": "Juventus",
    "KAA Gent": "KAA Gent",
    "KAS Eupen": "Eupen",
    "KRC Genk": "KRC Genk",
    "KSC Lokeren (-2020)": "Lokeren",
    "KV Kortrijk": "Kortrijk",
    "KV Mechelen": "Mechelen",
    "KV Oostende (-2024)": "Oostende",
    "KVC Westerlo": "Westerlo",
    "KVRS Waasland - SK Beveren": "Waasland-Beveren",
    "Kardemir Karabükspor": "Kardemir Karabükspor",
    "Karlsruher SC": "Karlsruhe",
    "Kasimpasa": "Kasimpasa",
    "Kayseri Erciyesspor (1966-2018)": "Erciyesspor",
    "Kayserispor": "Kayserispor",
    "Kocaelispor": "Kocaelispor",
    "Konyaspor": "Konyaspor",
    "LB Châteauroux": "Chateauroux",
    "LOSC Lille": "Lille",
    "LR Vicenza": "Vicenza",
    "Le Havre AC": "Le Havre",
    "Le Mans FC": "Le Mans",
    "Leeds United": "Leeds United",
    "Leicester City": "Leicester City",
    "Levadiakos": "Levadeiakos",
    "Levante UD": "Levante UD",
    "Lierse SK (-2018)": "Lierse",
    "Liverpool FC": "Liverpool",
    "Lorca FC": "Lorca",
    "Luton Town": "Luton Town",
    "MKE Ankaragücü": "MKE Ankaragücü",
    "MSV Duisburg": "Duisburg",
    "Manchester City": "Manchester City",
    "Manchester United": "Manchester United",
    "Mantova 1911": "Mantova",
    "Mersin Idmanyurdu": "Mersin Idman Yurdu",
    "Middlesbrough FC": "Middlesbrough",
    "Millwall FC": "Millwall",
    "Milton Keynes Dons": "Milton Keynes Dons",
    "Modena FC": "Modena",
    "Montpellier HSC": "Montpellier",
    "Moreirense FC": "Moreirense",
    "Mouscron-Péruwelz": "Mouscron",
    "Málaga CF": "Málaga",
    "NAC Breda": "NAC Breda",
    "NEC Nijmegen": "Nijmegen",
    "Newcastle United": "Newcastle United",
    "Niki Volos": "Niki Volos",
    "Norwich City": "Norwich City",
    "Nottingham Forest": "Nottingham Forest",
    "Novara Calcio 1908": "Novara",
    "Nîmes Olympique": "Nîmes Olympique",
    "OFI Crete": "OFI Crete",
    "OGC Nice": "OGC Nice",
    "Olympiacos Piraeus": "Olympiacos Piraeus",
    "Olympique Lyon": "Olympique Lyon",
    "Olympique Marseille": "Marseille",
    "Osmanlispor FK": "Osmanlispor",
    "Oud-Heverlee Leuven": "Oud-Heverlee Leuven",
    "Oxford United": "Oxford",
    "PAE Veria": "Veria",
    "PAOK Thessaloniki": "PAOK Thessaloniki",
    "PAS Giannina": "Giannina",
    "PAS Lamia 1964": "Lamia",
    "PEC Zwolle": "Zwolle",
    "PSV Eindhoven": "PSV Eindhoven",
    "Palermo FC": "Palermo",
    "Panathinaikos": "Panathinaikos",
    "Panetolikos": "Panetolikos",
    "Panionios FC": "Panionios",
    "Panserraikos": "Panserraikos",
    "Panthrakikos": "Panthrakikos",
    "Paris FC": "Paris FC",
    "Paris Saint-Germain": "Paris Saint-Germain",
    "Parma Calcio 1913": "Parma",
    "Parma FC": "Parma",
    "Pau FC": "Pau FC",
    "Pendikspor": "Pendikspor",
    "Peterborough United": "Peterboro",
    "Pisa Sporting Club": "Pisa Sporting Club",
    "Platanias Chania": "Platanias",
    "Plymouth Argyle": "Plymouth",
    "Pordenone Calcio": "Pordenone",
    "Portimonense SAD": "Portimonense",
    "Portsmouth FC": "Portsmouth",
    "Preston North End": "Preston",
    "Preußen Münster": "Preußen Münster",
    "Queens Park Rangers": "Queens Park Rangers",
    "Quevilly - Rouen Métropole": "Quevilly - Rouen Métropole",
    "Quevilly Rouen Métropole": "Quevilly Rouen",
    "RAAL La Louvière": "RAAL La Louviere",
    "RB Leipzig": "RB Leipzig",
    "RC Lens": "Lens",
    "RC Strasbourg Alsace": "Strasbourg",
    "RCD Espanyol Barcelona": "Barcelona",
    "RCD Mallorca": "RCD Mallorca",
    "RFC Seraing": "Seraing",
    "RKC Waalwijk": "Waalwijk",
    "RSC Anderlecht": "Anderlecht",
    "RWD Molenbeek": "RWD Molenbeek",
    "Racing Ferrol": "Ferrol",
    "Racing Santander": "Racing Santander",
    "Rayo Vallecano": "Rayo Vallecano",
    "Reading FC": "Reading",
    "Real Betis Balompié": "Real Betis",
    "Real Madrid": "Real Madrid",
    "Real Oviedo": "Oviedo",
    "Real Sociedad": "Real Sociedad",
    "Real Sociedad B": "Real Sociedad",
    "Real Valladolid CF": "Real Valladolid",
    "Real Zaragoza": "Real Zaragoza",
    "Recreativo Huelva": "Recreativo Huelva",
    "Red Star FC": "Red Star",
    "Reggina 1914": "Reggina",
    "Rio Ave FC": "Rio Ave",
    "Roda JC Kerkrade": "Roda JC Kerkrade",
    "Rodez AF": "Rodez",
    "Rotherham United": "Rotherham",
    "Royal Antwerp FC": "Antwerp",
    "Royal Charleroi SC": "Charleroi",
    "Royal Excel Mouscron (-2022)": "Mouscron",
    "SBV Excelsior": "Excelsior",
    "SC Bastia": "Bastia",
    "SC Braga": "Sp Braga",
    "SC Cambuur Leeuwarden": "Cambuur",
    "SC Farense": "Farense",
    "SC Freiburg": "SC Freiburg",
    "SC Heerenveen": "Heerenveen",
    "SC Paderborn 07": "Paderborn",
    "SC Telstar": "Telstar",
    "SD Amorebieta": "Amorebieta",
    "SD Eibar": "Eibar",
    "SD Huesca": "Huesca",
    "SD Ponferradina": "Ponferradina",
    "SG Dynamo Dresden": "Dresden",
    "SL Benfica": "Benfica",
    "SM Caen": "SM Caen",
    "SPAL": "Spal",
    "SPAL 2013": "Spal",
    "SS Juve Stabia": "Juve Stabia",
    "SS Lazio": "Lazio",
    "SS Virtus Lanciano": "Virtus Lanciano",
    "SSC Bari": "SSC Bari",
    "SSC Napoli": "Napoli",
    "SSV Jahn Regensburg": "Regensburg",
    "SSV Ulm 1846": "SSV Ulm 1846",
    "SV 07 Elversberg": "Elversberg",
    "SV Darmstadt 98": "SV Darmstadt 98",
    "SV Sandhausen": "Sandhausen",
    "SV Wehen Wiesbaden": "Wehen",
    "SV Werder Bremen": "Werder Bremen",
    "Samsunspor": "Samsunspor",
    "Sevilla Atlético": "Sevilla",
    "Sevilla FC": "Sevilla",
    "Sheffield United": "Sheffield United",
    "Sheffield Wednesday": "Sheffield Weds",
    "Sint-Truidense VV": "Sint-Truidense VV",
    "Sivasspor": "Sivasspor",
    "Skoda Xanthi": "Xanthi",
    "Southampton FC": "Southampton",
    "SpVgg Greuther Fürth": "Greuther Furth",
    "Sparta Rotterdam": "Sparta Rotterdam",
    "Spezia Calcio": "Spezia",
    "Sporting CP": "Sporting CP",
    "Sporting Gijón": "Sporting Gijón",
    "Stade Brestois 29": "Brest",
    "Stade Lavallois": "Laval",
    "Stade Reims": "Reims",
    "Stade Rennais FC": "Stade Rennais FC",
    "Standard Liège": "Standard",
    "Stoke City": "Stoke City",
    "Sunderland AFC": "Sunderland",
    "Swansea City": "Swansea City",
    "TSG 1899 Hoffenheim": "TSG Hoffenheim",
    "TSV 1860 Munich": "TSV 1860 Munich",
    "Ternana Calcio": "Ternana",
    "Ternana Unicusano Calcio": "Ternana",
    "Torino FC": "Torino",
    "Tottenham Hotspur": "Tottenham Hotspur",
    "Tours FC": "Tours",
    "Trabzonspor": "Trabzonspor",
    "Trapani Calcio": "Trapani",
    "UC Sampdoria": "Sampdoria",
    "UCAM Murcia CF": "UCAM Murcia",
    "UD Almería": "Almería",
    "UD Ibiza": "Ibiza",
    "UD Las Palmas": "UD Las Palmas",
    "UD Logroñés": "UD Logroñés",
    "UE Llagostera": "Llagostera",
    "US Alessandria Calcio 1912": "Alessandria",
    "US Avellino 1912": "Avellino",
    "US Boulogne": "Boulogne",
    "US Catanzaro": "Catanzaro",
    "US Concarneau": "Concarneau",
    "US Cremonese": "Cremonese",
    "US Créteil-Lusitanos": "US Créteil-Lusitanos",
    "US Latina Calcio": "Latina",
    "US Lecce": "Lecce",
    "US Orléans": "US Orléans",
    "US Palermo": "Palermo",
    "US Salernitana 1919": "Salernitana",
    "US Sassuolo": "Sassuolo",
    "USL Dunkerque": "Dunkerque",
    "Udinese Calcio": "Udinese",
    "Union Saint-Gilloise": "Union Saint-Gilloise",
    "VVV-Venlo": "VVV Venlo",
    "Valencia CF": "Valencia",
    "Valenciennes FC": "Valenciennes",
    "Varese 1910": "Varese",
    "Venezia FC": "Venezia",
    "VfB Stuttgart": "VfB Stuttgart",
    "VfL Bochum": "VfL Bochum",
    "VfL Osnabrück": "Osnabruck",
    "VfL Wolfsburg": "VfL Wolfsburg",
    "VfR Aalen": "Aalen",
    "Vicenza Calcio": "Vicenza",
    "Villarreal CF": "Villarreal",
    "Villarreal CF B": "Villarreal",
    "Virtus Entella": "Virtus Entella",
    "Vitesse Arnhem": "Vitesse",
    "Vitória Guimarães SC": "Vitória Guimarães SC",
    "Vitória Setúbal FC": "Vitória Setúbal FC",
    "Volos NFC": "Volos NFC",
    "Watford FC": "Watford",
    "West Bromwich Albion": "West Bromwich Albion",
    "West Ham United": "West Ham United",
    "Wigan Athletic": "Wigan",
    "Willem II Tilburg": "Willem II",
    "Wolverhampton Wanderers": "Wolverhampton Wanderers",
    "Wrexham AFC": "Wrexham",
    "Wycombe Wanderers": "Wycombe",
    "Würzburger Kickers": "Wurzburger Kickers",
    "Xanthi FC": "Xanthi",
    "Yeni Malatyaspor": "Yeni Malatyaspor",
    "Zulte Waregem": "Waregem",
    "Ümraniyespor": "Umraniyespor",
}


def normalize_team_name(team_name):
    """
    Normaliza el nombre de un equipo usando el diccionario TEAM_NAME_MAPPING.
    Si el equipo no está en el diccionario, se devuelve el nombre original (con espacios en los extremos quitados).
    """
    if not isinstance(team_name, str):
        return team_name
    
    team_name = team_name.strip()
    return TEAM_NAME_MAPPING.get(team_name, team_name)
